/// Static list of common dog breeds — used in DogSetupScreen and DogEditScreen.
class DogBreeds {
  DogBreeds._();

  static const List<String> all = [
    'Akita',
    'Basenji',
    'Basset Hound',
    'Beagle',
    'Berger Allemand',
    'Berger Australien',
    'Berger Belge Malinois',
    'Berger Blanc Suisse',
    'Bichon Frisé',
    'Border Collie',
    'Boston Terrier',
    'Bouledogue Français',
    'Bouledogue Anglais',
    'Boxer',
    'Braque de Weimar',
    'Briard',
    'Bull Terrier',
    'Cairn Terrier',
    'Cavalier King Charles',
    'Chihuahua',
    'Chow-Chow',
    'Cocker Anglais',
    'Cocker Américain',
    'Colley',
    'Dalmatien',
    'Dobermann',
    'Dogue Allemand',
    'Dogue de Bordeaux',
    'Épagneul Breton',
    'Fox Terrier',
    'Golden Retriever',
    'Greyhound',
    'Husky Sibérien',
    'Jack Russell Terrier',
    'Labrador Retriever',
    'Leonberg',
    'Lévrier Afghan',
    'Lhassa Apso',
    'Maltais',
    'Mastiff',
    'Montagne des Pyrénées',
    'Pinscher Nain',
    'Pitbull',
    'Pointer',
    'Poméranien',
    'Caniche Toy',
    'Caniche Moyen',
    'Caniche Grand',
    'Rottweiler',
    'Saint-Bernard',
    'Samoyède',
    'Setter Irlandais',
    'Shiba Inu',
    'Shih Tzu',
    'Spitz Nain',
    'Staffordshire Bull Terrier',
    'Teckel',
    'Terre-Neuve',
    'Westie',
    'Whippet',
    'Yorkshire Terrier',
    'Autre',
  ];
}
